recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, about_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('about/', about_view, name='about')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import recipe_home, RecipeListView, RecipeDetailView, records

app_name = 'recipes'

urlpatterns = [
    path('', recipe_home, name='home'),
    path('recipes/', RecipeListView.as_view(), name='list'),
    path('recipes/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('records/', records, name='records')
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Recipe(models.Model):
    category_choices = [
        ('main', 'Main'),
        ('side', 'Side'),
        ('dessert', 'Dessert')
    ]

    name = models.CharField(max_length=120)
    category = models.CharField(max_length=12, choices=category_choices, default='main')
    cooking_time = models.FloatField(help_text='In minutes')
    serving = models.PositiveIntegerField(default=1)
    ingredients = models.CharField(max_length=350, help_text='Ingredients must be separated by commas')
    directions = models.TextField()
    pic = models.URLField(default='https://liftlearning.com/wp-content/uploads/2020/09/default-image.png')

    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 10 and len(ingredients) < 4:
            difficulty = 'Easy'
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            difficulty = 'Medium'
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            difficulty = 'Hard'
        return difficulty
    
    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"Recipe ID: {self.id}, Name: {self.name}"

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return str(self.name)

recipes/forms.py
from django import forms

DIFFICULTY_CHOICES = (
    ('all', 'All'),
    ('easy', 'Easy'),
    ('medium', 'Medium'),
    ('intermediate', 'Intermediate'),
    ('hard', 'Hard')
)

CHART_CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart'),
)

class RecipeSearchForm(forms.Form):
    difficulty = forms.ChoiceField(choices=DIFFICULTY_CHOICES)
    chart_type = forms.ChoiceField(choices=CHART_CHOICES)

recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

def login_view(request):
    error_message = None
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('recipes:list')
        
        else:
            error_message = 'Oops, something went wrong!'

    context = {
            'form': form,
            'error_message': error_message
        }
    
    return render(request, 'auth/login.html', context)

def logout_view(request):
    logout(request)
    return render(request, 'auth/success.html')

def about_view(request):
    return render(request, 'about.html')

recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
import pandas as pd
from .models import Recipe
from .forms import RecipeSearchForm
from .utils import get_chart

# Create your views here.
def recipe_home(request):
    return render(request, 'recipes/recipe_home.html')

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/main.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'

@login_required
def records(request):
    form = RecipeSearchForm(request.POST or None)
    recipes_df = None
    chart = None

    if request.method == 'POST':
        difficulty = request.POST.get('difficulty')
        chart_type = request.POST.get('chart_type')

        all_records = Recipe.objects.all()
        id_searched = []
        for obj in all_records:
            if obj.calculate_difficulty().lower() == difficulty:
                id_searched.append(obj.id)
        qs = all_records.filter(id__in=id_searched)

        if qs:
            recipes_df = pd.DataFrame(qs.values())
            # Hide 'direction' and 'pic' fields
            recipes_df = recipes_df.loc[:, ~recipes_df.columns.isin(['directions', 'pic'])]
            chart = get_chart(chart_type, recipes_df, labels=recipes_df['category'].values)
            recipes_df = recipes_df.to_html()
        elif difficulty == 'all':
            recipes_df = pd.DataFrame(all_records.values())
            # Hide 'direction' and 'pic' fields
            recipes_df = recipes_df.loc[:, ~recipes_df.columns.isin(['directions', 'pic'])]
            chart = get_chart(chart_type, recipes_df, labels=recipes_df['category'].values)
            recipes_df = recipes_df.to_html()

    context = {
        'form' : form,
        'recipes_df' : recipes_df,
        'chart' : chart
    }

    return render(request, 'recipes/records.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

recipes/templates/recipes/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{object.name}} Recipe</title>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Source+Sans+Pro:wght@300;400;700&display=swap"
        rel="stylesheet">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'recipes/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/recipe.css' %}">
</head>

<body>
    <header>
        <nav>
            <p><a href="{% url 'recipes:home' %}">Recipe App</a></p>
            <div role="menubar" class="nav__items">
                <ul class="nav-list">
                    <li role="presentation">
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'recipes:records' %}">Search</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <h1 class="detail__title">{{object.name}} Recipe</h1>
    <main class="detail__container">
        <section class="detail__info">
            <p><span class="label">Category:</span>{{object.category}}</p>
            <p><span class="label">Serving:</span>{{object.serving}}</p>
            <p><span class="label">Cooking Time:</span>{{object.cooking_time}} mins</p>
            <p><span class="label">Difficulty:</span>{{object.calculate_difficulty}}</p>
            <p class="label--ingredients"><span class="label">Ingredients:</span></p>
            <p>{{object.ingredients}}</p>
        </section>
        <section class="detail__directions">
            <div class="detail__img-box">
                <img src="{{object.pic}}" alt="{{object.name}}">
            </div>
            <p class="label--directions"><span class="label">Directions:</span></p>
            <p>
                {{object.directions}}
            </p>
        </section>
    </main>

    <footer>
        <small>&copy; Miki Akuta 2023</small>
        <a href="https://github.com/Mikkobelly" target="_blank" class="media-link">
            <!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
            <svg style="enable-background:new 0 0 512 512;" version="1.1" viewBox="0 0 512 512" xml:space="preserve"
                xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="media">
                <g>
                    <path class="st0" d="M256,32C132.3,32,32,134.8,32,261.7c0,101.5,64.2,187.5,153.2,217.9c11.2,2.1,15.3-5,15.3-11.1
                           c0-5.5-0.2-19.9-0.3-39.1c-62.3,13.9-75.5-30.8-75.5-30.8c-10.2-26.5-24.9-33.6-24.9-33.6c-20.3-14.3,1.5-14,1.5-14   
                           c22.5,1.6,34.3,23.7,34.3,23.7c20,35.1,52.4,25,65.2,19.1c2-14.8,7.8-25,14.2-30.7c-49.7-5.8-102-25.5-102-113.5   
                           c0-25.1,8.7-45.6,23-61.6c-2.3-5.8-10-29.2,2.2-60.8c0,0,18.8-6.2,61.6,23.5c17.9-5.1,37-7.6,56.1-7.7c19,0.1,38.2,2.6,56.1,7.7   
                           c42.8-29.7,61.5-23.5,61.5-23.5c12.2,31.6,4.5,55,2.2,60.8c14.3,16.1,23,36.6,23,61.6c0,88.2-52.4,107.6-102.3,113.3   
                           c8,7.1,15.2,21.1,15.2,42.5c0,30.7-0.3,55.5-0.3,63c0,6.1,4,13.3,15.4,11C415.9,449.1,480,363.1,480,261.7   
                           C480,134.8,379.7,32,256,32z" />
                </g>
            </svg>
        </a>
    </footer>
</body>

</html>

recipes/templates/recipes/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recipe List</title>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Source+Sans+Pro:wght@300;400;700&display=swap"
        rel="stylesheet">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'recipes/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/recipe.css' %}">
</head>

<body>
    <header>
        <nav>
            <p><a href="{% url 'recipes:home' %}">Recipe App</a></p>
            <div role="menubar" class="nav__items">
                <ul class="nav-list">
                    <li role="presentation">
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'recipes:records' %}">Search</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <h1 class="main__title"></h1>
    <main class="main__container">
        {% for object in object_list %}
        <div class="recipe__card">
            <div class="recipe__img-box">
                <img src="{{object.pic}}" alt="{{object.name}}" width="150">
            </div>
            <div class="inner__container">
                <a href="{{object.get_absolute_url}}">
                    <h3 class="recipe__name">{{object.name}}</h3>
                </a>
                <p class="recipe__difficulty">{{object.calculate_difficulty}}</p>
            </div>
        </div>
        {% endfor %}
    </main>

    <footer>
        <small>&copy; Miki Akuta 2023</small>
        <a href="https://github.com/Mikkobelly" target="_blank" class="media-link">
            <!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
            <svg style="enable-background:new 0 0 512 512;" version="1.1" viewBox="0 0 512 512" xml:space="preserve"
                xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="media">
                <g>
                    <path class="st0" d="M256,32C132.3,32,32,134.8,32,261.7c0,101.5,64.2,187.5,153.2,217.9c11.2,2.1,15.3-5,15.3-11.1
                           c0-5.5-0.2-19.9-0.3-39.1c-62.3,13.9-75.5-30.8-75.5-30.8c-10.2-26.5-24.9-33.6-24.9-33.6c-20.3-14.3,1.5-14,1.5-14   
                           c22.5,1.6,34.3,23.7,34.3,23.7c20,35.1,52.4,25,65.2,19.1c2-14.8,7.8-25,14.2-30.7c-49.7-5.8-102-25.5-102-113.5   
                           c0-25.1,8.7-45.6,23-61.6c-2.3-5.8-10-29.2,2.2-60.8c0,0,18.8-6.2,61.6,23.5c17.9-5.1,37-7.6,56.1-7.7c19,0.1,38.2,2.6,56.1,7.7   
                           c42.8-29.7,61.5-23.5,61.5-23.5c12.2,31.6,4.5,55,2.2,60.8c14.3,16.1,23,36.6,23,61.6c0,88.2-52.4,107.6-102.3,113.3   
                           c8,7.1,15.2,21.1,15.2,42.5c0,30.7-0.3,55.5-0.3,63c0,6.1,4,13.3,15.4,11C415.9,449.1,480,363.1,480,261.7   
                           C480,134.8,379.7,32,256,32z" />
                </g>
            </svg>
        </a>
    </footer>
</body>

</html>

recipes/templates/recipes/recipe_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recipe App Home</title>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Source+Sans+Pro:wght@300;400;700&display=swap"
        rel="stylesheet">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'recipes/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/home.css' %}">
</head>

<body>
    <header>
        <nav>
            <p><a href="#">Recipe App</a></p>
            <div role="menubar" class="nav__items">
                <ul class="nav-list">
                    <li role="presentation">
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'recipes:records' %}">Search</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'login' %}" role="menuitem">Log in</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="main-container">
        <div class="main-img__box">
            <picture>
                <source srcset="{% static 'recipes/images/cooking-mobile.jpg'%}" media="(max-width: 50.25em)">
                <img src="{% static 'recipes/images/cooking.jpg'%}" alt="cooking">
            </picture>
        </div>
        <div class="main-content">
            <h2>
                <q>Every recipes, created by millions of home cooks.</q>
            </h2>
            <h1>What shall we cook?</h1>
            <a href="{% url 'login' %}" class="start__btn">Get started / Log in</a>
            <a href="{% url 'recipes:list' %}" class="signup__link">Already logged in? See all reipces</a>
        </div>
    </main>

    <footer>
        <small>&copy; Miki Akuta 2023</small>
        <a href="https://github.com/Mikkobelly" target="_blank" class="media-link">
            <!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
            <svg style="enable-background:new 0 0 512 512;" version="1.1" viewBox="0 0 512 512" xml:space="preserve"
                xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="media">
                <g>
                    <path class="st0" d="M256,32C132.3,32,32,134.8,32,261.7c0,101.5,64.2,187.5,153.2,217.9c11.2,2.1,15.3-5,15.3-11.1
                           c0-5.5-0.2-19.9-0.3-39.1c-62.3,13.9-75.5-30.8-75.5-30.8c-10.2-26.5-24.9-33.6-24.9-33.6c-20.3-14.3,1.5-14,1.5-14   
                           c22.5,1.6,34.3,23.7,34.3,23.7c20,35.1,52.4,25,65.2,19.1c2-14.8,7.8-25,14.2-30.7c-49.7-5.8-102-25.5-102-113.5   
                           c0-25.1,8.7-45.6,23-61.6c-2.3-5.8-10-29.2,2.2-60.8c0,0,18.8-6.2,61.6,23.5c17.9-5.1,37-7.6,56.1-7.7c19,0.1,38.2,2.6,56.1,7.7   
                           c42.8-29.7,61.5-23.5,61.5-23.5c12.2,31.6,4.5,55,2.2,60.8c14.3,16.1,23,36.6,23,61.6c0,88.2-52.4,107.6-102.3,113.3   
                           c8,7.1,15.2,21.1,15.2,42.5c0,30.7-0.3,55.5-0.3,63c0,6.1,4,13.3,15.4,11C415.9,449.1,480,363.1,480,261.7   
                           C480,134.8,379.7,32,256,32z" />
                </g>
            </svg>
        </a>
    </footer>
</body>

</html>

recipes/templates/recipes/records.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recipe Search</title>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Source+Sans+Pro:wght@300;400;700&display=swap"
        rel="stylesheet">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'recipes/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/records.css' %}">
</head>

<body>
    <header>
        <nav>
            <p><a href="{% url 'recipes:home' %}">Recipe App</a></p>
            <div role="menubar" class="nav__items">
                <ul class="nav-list">
                    <li role="presentation">
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'recipes:list' %}">Recipes</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <h1 class="records__title">Search Recipes</h1>
    <main class="records__container">
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <button type="submit">Search</button>
        </form>
        <br>
        {% if recipes_df %}
        {{ recipes_df | safe}}
        <br>
        <img src="data:image/png;base64, {{chart|safe}}" alt="chart">
        {% else %}
        <h3>No data found</h3>
        {% endif %}
    </main>

    <footer>
        <small>&copy; Miki Akuta 2023</small>
        <a href="https://github.com/Mikkobelly" target="_blank" class="media-link">
            <!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
            <svg style="enable-background:new 0 0 512 512;" version="1.1" viewBox="0 0 512 512" xml:space="preserve"
                xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="media">
                <g>
                    <path class="st0" d="M256,32C132.3,32,32,134.8,32,261.7c0,101.5,64.2,187.5,153.2,217.9c11.2,2.1,15.3-5,15.3-11.1
                           c0-5.5-0.2-19.9-0.3-39.1c-62.3,13.9-75.5-30.8-75.5-30.8c-10.2-26.5-24.9-33.6-24.9-33.6c-20.3-14.3,1.5-14,1.5-14   
                           c22.5,1.6,34.3,23.7,34.3,23.7c20,35.1,52.4,25,65.2,19.1c2-14.8,7.8-25,14.2-30.7c-49.7-5.8-102-25.5-102-113.5   
                           c0-25.1,8.7-45.6,23-61.6c-2.3-5.8-10-29.2,2.2-60.8c0,0,18.8-6.2,61.6,23.5c17.9-5.1,37-7.6,56.1-7.7c19,0.1,38.2,2.6,56.1,7.7   
                           c42.8-29.7,61.5-23.5,61.5-23.5c12.2,31.6,4.5,55,2.2,60.8c14.3,16.1,23,36.6,23,61.6c0,88.2-52.4,107.6-102.3,113.3   
                           c8,7.1,15.2,21.1,15.2,42.5c0,30.7-0.3,55.5-0.3,63c0,6.1,4,13.3,15.4,11C415.9,449.1,480,363.1,480,261.7   
                           C480,134.8,379.7,32,256,32z" />
                </g>
            </svg>
        </a>
    </footer>
</body>

</html>

templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About me</title>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Source+Sans+Pro:wght@300;400;700&display=swap"
        rel="stylesheet">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'recipes/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/auth.css' %}">
</head>

<body>
    <header>
        <nav>
            <p><a href="{% url 'recipes:home' %}">Recipe App</a></p>
            <div role="menubar" class="nav__items">
                <ul class="nav-list">
                    <li role="presentation">
                        <a href="{% url 'recipes:list' %}">Recipes</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'recipes:records' %}">Search</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="about__container">
        <h1 class="about__title">Miki Akuta</h1>
        <h2>Developer of the Recipe App</h2>
        <p class="bio">
            Hi, I am an adventurous and creative web developer from Japan. I stepped into the world of software
            development
            after being a professional ballet dancer for 8 years.
            I was able to hone my skills as an artist and bring inspiration to my parts. Now as a web
            developer, I enjoy to continue evolving in a new form of art using my versatile skill.
            I am keen to put my vision, ideas and artistic talent to enhance the way technology is used and collaborate
            with people who are passionate about pursuing their creative dreams!
        </p>
        <div class="imgs__container">
            <div>
                <img src="{% static 'recipes/images/Miki_chair_resized.jpg' %}" alt="Miki's photoshot with chair"
                    class="img--1">
            </div>
            <div>
                <img src="{% static 'recipes/images/Miki_DL_resized.jpg' %}"
                    alt="Miki's photoshot in ballet 'Dangerous Liaisons'" class="img--2">
            </div>
        </div>
        <div class="link__box">
            <a href="https://mikkobelly.github.io/MySite/" target="_blank" class="portfolio__link">Check out my
                portfolio</a>
        </div>
    </main>

    <footer>
        <small>&copy; Miki Akuta 2023</small>
        <a href="https://github.com/Mikkobelly" target="_blank" class="media-link">
            <!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
            <svg style="enable-background:new 0 0 512 512;" version="1.1" viewBox="0 0 512 512" xml:space="preserve"
                xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="media">
                <g>
                    <path class="st0" d="M256,32C132.3,32,32,134.8,32,261.7c0,101.5,64.2,187.5,153.2,217.9c11.2,2.1,15.3-5,15.3-11.1
                           c0-5.5-0.2-19.9-0.3-39.1c-62.3,13.9-75.5-30.8-75.5-30.8c-10.2-26.5-24.9-33.6-24.9-33.6c-20.3-14.3,1.5-14,1.5-14   
                           c22.5,1.6,34.3,23.7,34.3,23.7c20,35.1,52.4,25,65.2,19.1c2-14.8,7.8-25,14.2-30.7c-49.7-5.8-102-25.5-102-113.5   
                           c0-25.1,8.7-45.6,23-61.6c-2.3-5.8-10-29.2,2.2-60.8c0,0,18.8-6.2,61.6,23.5c17.9-5.1,37-7.6,56.1-7.7c19,0.1,38.2,2.6,56.1,7.7   
                           c42.8-29.7,61.5-23.5,61.5-23.5c12.2,31.6,4.5,55,2.2,60.8c14.3,16.1,23,36.6,23,61.6c0,88.2-52.4,107.6-102.3,113.3   
                           c8,7.1,15.2,21.1,15.2,42.5c0,30.7-0.3,55.5-0.3,63c0,6.1,4,13.3,15.4,11C415.9,449.1,480,363.1,480,261.7   
                           C480,134.8,379.7,32,256,32z" />
                </g>
            </svg>
        </a>
    </footer>
</body>

</html>